package io.quizforge.core;

public enum ErrorCode {
    WORKSPACE_NOT_FOUND,
    INVALID_WORKSPACE_NAME,
    UNSUPPORTED_MATERIAL_FORMAT,
    EMPTY_MATERIAL,
    MATERIAL_TOO_LARGE,
    MATERIAL_READ_FAILED,
    MATERIAL_STORAGE_FAILED,
    MATERIAL_NOT_FOUND,
    PERSISTENCE_FAILED,
    AI_PROVIDER_NOT_CONFIGURED,
    AI_PROVIDER_CREDENTIAL_MISSING,
    AI_PROVIDER_AUTHENTICATION_FAILED,
    AI_PROVIDER_RATE_LIMITED,
    AI_PROVIDER_TIMEOUT,
    AI_PROVIDER_UNAVAILABLE,
    AI_PROVIDER_INVALID_RESPONSE,
    NO_MATERIAL_SELECTED,
    MATERIAL_NOT_IN_WORKSPACE,
    DOCUMENT_INPUT_TOO_LARGE,
    STANDARD_DOCUMENT_PARSE_FAILED,
    STANDARD_DOCUMENT_VALIDATION_FAILED,
    STANDARD_DOCUMENT_STORAGE_FAILED,
    STANDARD_DOCUMENT_NOT_FOUND
}
