package io.quizforge.core;

public enum ErrorCode {
    WORKSPACE_NOT_FOUND,
    WORKSPACE_STORAGE_FAILED,
    INVALID_WORKSPACE_NAME,
    PERSISTENCE_FAILED,
    AI_PROVIDER_NOT_CONFIGURED,
    AI_PROVIDER_CREDENTIAL_MISSING,
    AI_PROVIDER_AUTHENTICATION_FAILED,
    AI_PROVIDER_RATE_LIMITED,
    AI_PROVIDER_TIMEOUT,
    AI_PROVIDER_UNAVAILABLE,
    AI_PROVIDER_INVALID_RESPONSE,
    REGISTERED_MARKDOWN_STORAGE_FAILED,
    QUESTION_BANK_FILE_INVALID,
    QUESTION_BANK_STORAGE_FAILED,
    INVALID_PACKAGE,
    MISSING_MANIFEST,
    MISSING_BANK,
    UNSUPPORTED_FORMAT,
    UNSUPPORTED_SCHEMA_VERSION,
    INVALID_MANIFEST,
    INVALID_BANK,
    MISSING_RESOURCE,
    RESOURCE_HASH_MISMATCH,
    UNSAFE_ZIP_ENTRY,
    PACKAGE_LIMIT_EXCEEDED
}
